"""Add user entity tables

Revision ID: 0002
Revises: 0001_product_model_tweaks
Create Date: 2026-05-12 11:06:57.279474
"""

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001_product_model_tweaks"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
